name: Deploy Documentation

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install mkdocs and mkdocs-material
        run: pip install mkdocs mkdocs-material

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: 'latest'

      - name: Install MatBox
        uses: ehennestad/matbox-actions/install-matbox@v1

      - name: Build Documentation (MATLAB)
        uses: matlab-actions/run-command@v2
        with:
          command: |
            disp(['Current directory: ' pwd]);
            system('ls -al');
            matbox.installRequirements(pwd);
            tools_path = fullfile(pwd, 'tools');
            if exist(tools_path, 'dir')
                disp(['Listing contents of ' tools_path ':']);
                system(['ls -al "' tools_path '"']);
                disp(['Adding ' tools_path ' and subdirectories to path.']);
                addpath(genpath(tools_path));
            else
                disp(['Directory ' tools_path ' does not exist.']);
            end
            addpath(genpath(fullfile(pwd, 'src')));
            ndi_Init();
            ndi.docs.build();
            quit;

      - name: Prepare mkdocs files
        run: |
          mv src/ndi/docs/NDI-matlab/mkdocs.yml ./mkdocs.yml
          mv src/ndi/docs ./docs

      - name: Configure Git
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
